#!/bin/bash

invoke()
{
	cmd="$1"
	shift

	rest="$@"

	if [[ "$cmd" == "set" ]] || [[ "$cmd" == "clear" ]] || [[ "$cmd" == "url" && -n $rest ]]; then
		# Eval the output bash script:
		echo EVAL!
		./http-cli "$cmd" "$rest"
		eval `./http-cli "$cmd" $rest`
	else
		# No eval required:
		./http-cli "$cmd" $rest
	fi
}

if [ -z "$1" ]; then
	./http-cli
else
	invoke "$@"
fi
